### In this notebook we will use the raw data to create a simulated different dataset to test datadrift.

In [121]:
import pandas as pd
import numpy as np

In [133]:
df = pd.read_csv("..\\data\\01_raw\\Hotel_H2.csv")
df.tail()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
79325,0,23,2017,August,35,30,2,5,2,0.0,...,No Deposit,394,NULL,0,Transient,96.14,0,0,Check-Out,2017-09-06
79326,0,102,2017,August,35,31,2,5,3,0.0,...,No Deposit,9,NULL,0,Transient,225.43,0,2,Check-Out,2017-09-07
79327,0,34,2017,August,35,31,2,5,2,0.0,...,No Deposit,9,NULL,0,Transient,157.71,0,4,Check-Out,2017-09-07
79328,0,109,2017,August,35,31,2,5,2,0.0,...,No Deposit,89,NULL,0,Transient,104.40,0,0,Check-Out,2017-09-07
79329,0,205,2017,August,35,29,2,7,2,0.0,...,No Deposit,9,NULL,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [134]:
data = df[-10000:]

In [135]:
data.index = [i+10000 for i in data.index]

We can not mess a lot with dates because it requires a lot of fiddling to get accurate dates according to week number, weekends, etc. So we will stay in 2017. We will change little things in the dataset so we can just test data drift and see how it affects scores. We will see an influx of British people and their ADR will increase.

In [136]:
data.columns

Index(['IsCanceled', 'LeadTime', 'ArrivalDateYear', 'ArrivalDateMonth',
       'ArrivalDateWeekNumber', 'ArrivalDateDayOfMonth',
       'StaysInWeekendNights', 'StaysInWeekNights', 'Adults', 'Children',
       'Babies', 'Meal', 'Country', 'MarketSegment', 'DistributionChannel',
       'IsRepeatedGuest', 'PreviousCancellations',
       'PreviousBookingsNotCanceled', 'ReservedRoomType', 'AssignedRoomType',
       'BookingChanges', 'DepositType', 'Agent', 'Company',
       'DaysInWaitingList', 'CustomerType', 'ADR', 'RequiredCarParkingSpaces',
       'TotalOfSpecialRequests', 'ReservationStatus', 'ReservationStatusDate'],
      dtype='object')

In [137]:
data

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
79330,0,248,2017,April,15,9,2,0,2,0.0,...,No Deposit,58,NULL,0,Transient-Party,80.00,0,1,Check-Out,2017-04-11
79331,0,248,2017,April,15,9,2,0,2,0.0,...,No Deposit,58,NULL,0,Transient-Party,80.00,0,1,Check-Out,2017-04-11
79332,0,63,2017,April,15,9,2,0,2,0.0,...,No Deposit,9,NULL,0,Transient,99.00,0,0,Check-Out,2017-04-11
79333,0,63,2017,April,15,9,2,0,2,0.0,...,No Deposit,9,NULL,0,Transient,99.00,0,0,Check-Out,2017-04-11
79334,0,248,2017,April,15,9,2,0,2,0.0,...,No Deposit,58,NULL,0,Transient-Party,80.00,0,1,Check-Out,2017-04-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89325,0,23,2017,August,35,30,2,5,2,0.0,...,No Deposit,394,NULL,0,Transient,96.14,0,0,Check-Out,2017-09-06
89326,0,102,2017,August,35,31,2,5,3,0.0,...,No Deposit,9,NULL,0,Transient,225.43,0,2,Check-Out,2017-09-07
89327,0,34,2017,August,35,31,2,5,2,0.0,...,No Deposit,9,NULL,0,Transient,157.71,0,4,Check-Out,2017-09-07
89328,0,109,2017,August,35,31,2,5,2,0.0,...,No Deposit,89,NULL,0,Transient,104.40,0,0,Check-Out,2017-09-07
89329,0,205,2017,August,35,29,2,7,2,0.0,...,No Deposit,9,NULL,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [138]:
data.loc[data.index[5000:],'Country'] = 'GBR'
data.loc[data.index[5000:],'ADR'] += 50

In [139]:
len(data.index[5000:])

5000

In [140]:
data.IsCanceled.value_counts()

0    9995
1       5
Name: IsCanceled, dtype: int64

Let's also pretend they cancel more (75% of the time).

In [141]:
data.loc[data.index[5000:],'IsCanceled'] = [np.random.choice([0, 1], p=[0.25, 0.75]) for i in range(5000)]

In [142]:
data.IsCanceled.value_counts()

0    6296
1    3704
Name: IsCanceled, dtype: int64

We have to create some specific lines because this is a small dataset and we need certain values to appear for later best columns in feature selection to exist that come from encoding.

Our fake dataset is created! Let's save it.

In [143]:
data.to_csv("..\\data\\01_raw\\data_predict.csv")